- name: create t2 instance
  hosts: localhost
  tasks:
    - name: create
      ec2:
        key_name: main
        instance_type: t2.micro
        image: ami-c7e0c82c
        region: eu-central-1
        #wait: yes
        #group: webserver
        #count: 3
        #vpc_subnet_id: subnet-29e63245
        #assign_public_ip: yes